### ISSUE TITLE
NoSuchMethodError: com.codename1.ui.Font.getAscent()

### ISSUE THREAD

**Issue by Munken** [shannah/CN1aChartEngine#8]
Hey Shannah

Just tried the latest build that should work with the latest pipeline. 

However I consistently get an exception
```
java.lang.NoSuchMethodError: com.codename1.ui.Font.getAscent()I
	at org.achartengine.compat.Canvas.drawText(Canvas.java:117)
	at org.achartengine.chart.AbstractChart.drawString(AbstractChart.java:170)
	at org.achartengine.chart.XYChart.drawText(XYChart.java:666)
	at org.achartengine.chart.XYChart.drawXTextLabels(XYChart.java:837)
	at org.achartengine.chart.XYChart.drawXLabels(XYChart.java:731)
	at org.achartengine.chart.XYChart.draw(XYChart.java:363)
	at org.achartengine.GraphicalView.onDraw(GraphicalView.java:195)
	at org.achartengine.compat.View$Peer.paint(View.java:126)
	at com.codename1.ui.Component.internalPaintImpl(Component.java:1252)
	at com.codename1.ui.Component.paintInternalImpl(Component.java:1226)
	at com.codename1.ui.Component.paintInternal(Component.java:1201)
```

I have checked the public API and there is no getAscent method listed.
https://codenameone.googlecode.com/svn/trunk/CodenameOne/javadoc/com/codename1/ui/Font.html

I have done a debug build to ensure that my CN1 libraries are up to date.

**Comment by shannah** [comment]
That is a relatively new method in CN1.  Make sure you have updated to the latest plugin and libraries (for codename one).

**Comment by Munken** [comment]
Do you know where one can find it?

Even the version in the ChartsDemo project in SVN don't have this method.

**Comment by shannah** [comment]
The libraries included in demo projects are always out of date.    It is in subversion, and I think it should be part of the current plugin.
